### ISSUE TITLE
Small issue in "Step 3. Extract unrelated samples"

### ISSUE THREAD

**Issue by daniel-hui** [rounakdey/FastSparseGRM#2]
Hi Rounak,

There seems to be a small issue in Step 3 when using Plink2. The delimiter seems to have been changed from space to tab for .fam files. This change seems to cause an error if the plink files were created using Plink2 instead of Plink1.9, which I believe is in line 131 of `getUnrels.R`:

`fam <- read.table(paste0(prefix.in,".fam"),sep=" ",header=F)`

Just wanted to let you know, thanks.

Daniel

**Comment by rounakdey** [comment]
Thanks for notifying. Fixed in the latest update.
