### ISSUE TITLE
A small issue in the runPipeline_wrapper.R

### ISSUE THREAD

**Issue by hmutanqilong** [rounakdey/FastSparseGRM#3]
Hi Rounak,
There seems to be an issue in runPipeline_wrapper.R. In Step 5, the updated function added the parameter --KINGformat.out, However, it didn't have been added in the runPipeline_wrapper.R at the same time.

**In runPipeline_wrapper.R**
`calcSparseGRM(prefix.in,file.score=paste0(prefix.out,".score"),file.train=paste0(prefix.temp.out,".unrels"),file.seg=paste0(prefix.temp.out,".seg"),no_pcs,num_threads,prefix.out,degree,block.size,max.related.block)`

**In calcSparseGRM_wrapper.R**
`calcSparseGRM(prefix.in,file.score,file.train,file.seg,no_pcs,num_threads,prefix.out,degree,block.size,max.related.block,KINGformat.out)`
Qilong

**Comment by rounakdey** [comment]
Fixed in the current update
