### ISSUE TITLE
FastSparseGRM installation

### ISSUE THREAD

**Issue by pthami07** [rounakdey/FastSparseGRM#6]
Hi Rounak,
I've been trying to install FastSparseGRM in several versions of R including 4.0.0, 4.0.2, 4.2.0, 4.3.0. I get this example error "package ‘FastSparseGRM’ is not available (for R version 4.0.2)". Which version of R does FastSparseGRM work in?
Kind regards,
Prisca.

**Comment by rounakdey** [comment]
Are you trying to install it through github, or through CRAN? The package is not available in CRAN, so install.packages("FastSparseGRM") command will not work. Please use the following command in a bash terminal to install.
```
git clone https://github.com/rounakdey/FastSparseGRM.git
R CMD INSTALL FastSparseGRM
```
FastSparseGRM works in all those R versions you tried.

**Comment by pthami07** [comment]
Thanks Rounak for that clarity. I realize that initially it was a HPC problem. I had issues with running the R CMD INSTALL in the login node so I tried CRAN. I've just managed to install through github in an interactive session. Thanks very much!

**Comment by rounakdey** [comment]
Glad that the issue is solved.
