### ISSUE TITLE
Issue in Step 3. extract unrelated samples

### ISSUE THREAD

**Issue by zoeychow777** [rounakdey/FastSparseGRM#9]
I finished Step 2 and got the .div file, but when I did Step 3, this error occurred:

> extractUnrelated(file.seg,file.div,prefix.in,degree,file.include,prefix.out)
[1] "Extracting the set of unrelated samples"
Error in `[.data.frame`(kin0, , c("ID1", "ID2", "PropIBD")) : 
  undefined columns selected

Here are the args:

> opt <- args$options
> print(opt)
$prefix.in
[1] "filtered"

$file.seg
[1] "test.segments.gz"

$file.div
[1] "ttt.divergence.div"

$degree
[1] 4

$file.include
[1] ""

$prefix.out
[1] "ttt2"

$help
[1] FALSE

Would you help me with this problem? Thank you!

**Comment by rounakdey** [comment]
The problem is here:
$file.seg
[1] "test.segments.gz"

The file.seg argument should be some filename.seg, not the segments.gz file. There should be a test.seg file in the output from step 1. (Also, you need to use that test.seg file for step 2 as well, and not the segments.gz file).

**Comment by zoeychow777** [comment]
Thank you so much for the prompt response! I got the test.segments.gz file from Step 1, and use this gz file in Step 2 and got the .div file. Step 2 run okay using gz file, would the .div file be a problem? Or I should re-do the Step 2? Also, it takes over 24h to run Step 2 for all UKBB participants, is it normal? Thanks again!

**Comment by rounakdey** [comment]
Yes, unfortunately you need to run step 2 again, it should be run using the `.seg` file, and not the `.segments.gz` file.
For all UKBB participants, use `nRandomSNPs=10000` when running step 2, it will be done in 3 hours or so on 30 CPUs. Don't use the default `nRandomSNPs=0` which means using all available SNPs. It is fine to use 10000 random SNPs for this step at such a large sample-size.

**Comment by zoeychow777** [comment]
I run step 2 again with .seg file, but it still shows the same error in Step 3. Here is the head of .div file and .seg file

<img width="866" alt="image" src="https://github.com/rounakdey/FastSparseGRM/assets/49321950/a1d1a333-4802-45bd-adbf-2aa9d72b0ad1">

**Comment by zoeychow777** [comment]
Do you have any idea why it's happening?

**Comment by rounakdey** [comment]
This is not the .seg file. This is a .segments file, very different. There should be a .seg file in the KING output, not .segments or .segments.gz, just .seg. You need to use that file.

**Comment by zoeychow777** [comment]
Great! Thank you so so much for answering all my questions with patience! All problems were solved and I got the results!

**Comment by rounakdey** [comment]
Great to know
